### PR TITLE
moved exercises into subdirectory

### PR DESCRIPTION
**Pull request by cyborgsphinx**
The issue is alive as #63, but it doesn't look like there's a corresponding pull request. Now there is.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks @cyborgsphinx! This is the very last active track that needs to move the exercises. It will be great to all the code that deals with the deprecated exercise locations.

The build is failing—would you have a chance to take a look at that?

**Comment by Insti** [comment]
I suspect the root `CMakelists.txt` file needs to be updated to reference the new exercise locations.

**Comment by cyborgsphinx** [comment]
I agree that the `CMakeLists.txt` file needs updating. I've never actually used cmake before, aside from executing `cmake -G "Unix Makefiles"`, so I'm not sure how to make it work. I've tried a few things, like just modifying the working directory, to no real success.

**Comment by patricksjackson** [comment]
[Something like this patch should work, though I didn't fully test it.](https://github.com/patricksjackson/xcpp/commit/62c7238dc3007462277f44ac5ae3ceb2fedf1ec1)

I can look up how to make a PR against this PR (?) tomorrow, but feel free to make those changes yourself if you get to it first.

**Comment by cyborgsphinx** [comment]
That seems to work. Thanks.

**Comment by patricksjackson** [comment]
LGTM 👍

**Comment by kytrinyx** [comment]
I'm going to go ahead and merge this. If it needs improvements later it can be done in a separate pull request. Thanks all :heart: :heart:

**Pull request merged**
