### PR TITLE
Created RESOURCES.md file

### PR DESCRIPTION
**Pull request by oalbe**
Hey there,
I've recently started the C++ track and seen there's a missing resources section in http://exercism.io/languages/cpp. I though I could make one since I know some helpful resources about C++, so here it is.

All this pull request includes is a new `RESOURCES.md` file with three resources that have helped me a lot. Hope other will find them helpful as well.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks! Would you mind squashing the commits?

I'll leave this for @LegalizeAdulthood to review for technical content.

**Comment by oalbe** [comment]
@kytrinyx Done. Sorry, I should have thought about it before making the pull request.

**Comment by kytrinyx** [comment]
Thanks @oalbe.

**Comment by LegalizeAdulthood** [comment]
LGTM, thanks!

**Pull request merged**
