### PR TITLE
Removing require_equal_containers.h

### PR DESCRIPTION
**Pull request by patricksjackson**
The use of require_equal_containers.h has been buggy for a while, and was totally broken for modern versions of Boost. This removes that and replaces it with builtin boost test macros. The error messages take a slight hit from what used to be there*, but this makes it actually work without having to maintain an undocumented hack of Boost.Test.

I will be trying to test this with different versions of Boost using Travis, as I'm not sure how many versions of Boost this supports. As long as it works with at least Boost 1.59 I think this is a good improvement, though the requirements for the repo/docs will need to be updated (they currently require only Boost 1.55).

*Error messages in all of the 'containers of containers' will only report that the two containers are non-equal, and not _what_ is different about them. It's a small loss to usability.

### CODE REVIEW

**Comment by patricksjackson** [comment]
Ok, Travis has been updated to pass, and the documentation is updated as well.

I will be merging this in a week unless someone raises a problem. This is a long-standing problem for the repo that made many of the tests unusable for anyone on a recent distro.

See #110, #111, #91.

**Comment by sunzenshen** [comment]
Branch works OK for me with: 

- OS X El Capitan 10.11.6
- AppleClang 8.0.0.8000038
- Boost version 106300

**Comment by patricksjackson** [comment]
I took another look through the documentation today, and added additional details around how to acquire Boost 1.59. I expect that after this change we may see a few people coming in who have a broken install (i.e. they've been using 1.55 and will then get a failed build once they get a new version), but it should not be that many people.

I expect that the vast majority of people are already using Boost 1.59+, as it is about 2 years old and every major Linux distro has updated by now (and the install process for Windows/Mac usually has people install the latest version). The notable exception is Ubuntu 16.04 LTS, which uses Boost 1.58. I've added explicit install instructions for that distro.

**Comment by Skarlso** [comment]
Awesomesauce!

**Pull request merged**
