### PR TITLE
Porting the circular buffer challenge.

### PR DESCRIPTION
**Pull request by TrophyNinjaShrub**

### CODE REVIEW

**Comment by k4rtik** [comment]
You might want to make an entry for this problem in `config.json` as well.

**Comment by TrophyNinjaShrub** [comment]
Thanks k4rtik! I added that change.

**Comment by kytrinyx** [comment]
Thanks! Would you mind squashing your commits into a single commit?

I'm leaving this for @LegalizeAdulthood to review and merge.

**Comment by TrophyNinjaShrub** [comment]
Squashed as per kytrinyx. Thanks for taking a look.

**Comment by LegalizeAdulthood** [comment]
Can you rebase onto the latest and resolve the conflicts?  I suspect it is because I accepted a PR that reordered the exercises: https://github.com/exercism/xcpp/pull/82

**Pull request closed without merging**
