### PR TITLE
Added ABOUT.md page

### PR DESCRIPTION
**Pull request by anuragaryan**
Added ABOUT.md page in docs folder.
Went through @LegalizeAdulthood's comment in #64 and tried to follow the instruction.
Please review.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks! I'm going to leave this for @LegalizeAdulthood to review, since he's familiar with the details.

**Comment by LegalizeAdulthood** [comment]
I will try to look at this soon.  Ping the comments here if you don't get a prompt reply from me :smile_cat:

**Comment by anuragaryan** [comment]
@LegalizeAdulthood Pinged. :smile:

**Comment by LegalizeAdulthood** [comment]
This looks good, but I have a couple nits to pick :smile_cat:.  I added them as comments on the commit.  If you could fix those two tiny things, that would be great!  Thanks for the contribution!

**Comment by anuragaryan** [comment]
@LegalizeAdulthood You've a keen eye for detail. :+1: Please review the modified file.

**Comment by anuragaryan** [comment]
@LegalizeAdulthood check this out.

**Comment by LegalizeAdulthood** [comment]
OK, I spotted one tiny thing, but I'm going to merge this and then just adjust it for myself :smile_cat:

Line 40 shouldn't begin with "And" is the tiny thing.

Thanks for the contribution!

**Pull request merged**
