### PR TITLE
 Add .editorConfig for consistency for WhiteSpace Usage

### PR DESCRIPTION
**Pull request by aswinmohanme**
Refrence Issue https://github.com/exercism/xcpp/issues/92

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thank you @aswinmohanme! (I'll leave this for @LegalizeAdulthood to review)

**Comment by aswinmohanme** [comment]
Thanks !
P.S : This is my second Pull Request . So Excited

**Comment by aswinmohanme** [comment]
3 days and Nothing. Did my commiy go to waste?

**Comment by aswinmohanme** [comment]
*commit

**Comment by patricksjackson** [comment]
This is not a rapidly developed repo, which should be obvious by the activity level around here. Please be a little patient :)

I will take a look at this and give you some feedback, but it will be a few days as I'm on vacation. (I haven't used EditorConfig before so it's not a matter of me just reading the commit.)

**Pull request merged**
